export const commands = {
  DeviceStatusReq: 0x01,
  DeviceStatus: 0x02,
  BusStatusReq: 0x03,
  BusStatus: 0x04,
  DiagMemoryRead: 0x06,
  DiagMemoryWrite: 0x07,
  DiagCodingRead: 0x08,
  DiagCodingWrite: 0x09,
  VehiculeCntrl: 0x0c,
  IgnitionStatusReq: 0x10,
  IgnitionStatus: 0x11,
  SensorStatusRq: 0x12 /* IKE sensor status */,
  SensorStatus: 0x13,
  CountryCodingReq: 0x14,
  CountryCoding: 0x15,
  OdometerReq: 0x16 /*"Odometer request"*/,
  Odometer: 0x17 /*"Odometer"*/,
  SpeedRpm: 0x18 /*"Speed/RPM"*/,
  Temperature: 0x19 /*"Temperature"*/,
  TextGong: 0x1a /*"IKE text display/Gong"*/,
  TextStatus: 0x1b /*"IKE text status"*/,
  Gong: 0x1c /*"IKE Gong"*/,
  TemperatureReq: 0x1d,
  TimeData: 0x1f,
  GTChangeUIReq: 0x20,
  GTChangeUI: 0x21,
  GTMenuBuffer: 0x22 /* Display text ack */,
  GTWriteTitle: 0x23 /* Display text */,
  ANZVUpdate: 0x24 /*"Update ANZV"*/,
  OBCSUpdate: 0x2a /*"On-Board Computer State Update"*/,
  TelephoneIndicator: 0x2b /*Telephone indicators*/,
  TelephoneStatus: 0x2c /* telephone status */,
  GTMenuSelect: 0x31,
  MFLButtons: 0x32 /*"MFL buttons"*/,
  DSPEqButton: 0x34 /*"DSP Equalizer Button"*/,
  GTDisplayRadioMenu: 0x37,
  CDStatusReq: 0x38 /*"CD status request"*/,
  CDStatus: 0x39 /*"CD status"*/,
  MFLButtons2: 0x3b /*"MFL buttons"*/,
  SDRSStatusReq: 0x3d /*"SDRS status request"*/,
  SDRSStatus: 0x3e /*"SDRS status"*/,
  OBCDSet: 0x40 /*"Set On-Board Computer Data"*/,
  OBCDReq: 0x41 /*"On-Board Computer Data Request"*/,
  GTScreenModeSet: 0x45,
  LCDClear: 0x46 /* LCD Clear*/,
  BMBTB0: 0x47 /*"BMBT buttons"*/,
  BMBTB1: 0x48 /*"BMBT buttons"*/,
  Knob: 0x49 /*"KNOB button"*/ /*this is for right knob turn, pressing know is BMBTB1 and ButtonMenuKnob*/,
  K7Ctrl: 0x4a /*Cassette control*/,
  K7Status: 0x4b /*"Cassette Status"*/,
  GTRadioTelevisionStatus: 0x4e,
  GTMonitorCtrl: 0x4f /* RGB control */,
  VehiculeDataReq: 0x53 /*"Vehicle data request"*/,
  VehiculeData: 0x54 /*"Vehicle data status"*/,
  LampStatusReq: 0x5a /*"Lamp status request"*/,
  LampStatus: 0x5b /*"Lamp Status"*/,
  InstrumentLightStatus: 0x5c /*"Instrument cluster lighting status"*/,
  InstrumentLightStatusReq: 0x5d,
  GTWriteIndex: 0x60,
  GTWriteIndexTMC: 0x61,
  GTWriteZone: 0x62,
  GTWriteStatic: 0x63,
  RainStatusReq: 0x71 /*"Rain sensor status request"*/,
  RemoteKeyButton: 0x72 /*"Remote Key buttons"*/,
  EWSKeyStatus: 0x74 /*"EWS key status"*/,
  DoorsWindowsStatusReq: 0x79 /*"Doors/windows status request"*/,
  DoorsWindowsStatus: 0x7a /*"Doors/windows status"*/,
  SHDStatus: 0x7c /*"SHD status"*/,
  DiagData: 0xa0 /*"DIAG data"*/,
  GTTelematicsCoordinates: 0xa2,
  GTTelematicsLocation: 0xa4,
  GTWriteWithCursor: 0xa5 /* screen text */,
  SpecialIndicatorsAck: 0xa6 /* IKE special indicators ack */,
  TMCStatusReq: 0xa7 /*"TMC status request"*/,
  TMCStatus: 0xa8,
  NavigationTelephoneData: 0xa9,
  NavigationCtrl: 0xaa /*"Navigation Control"*/,
  NavigationRemoteCtrl: 0xab /* Remote control status */,
  RDSChannels: 0xd4 /*RDS channel list*/,
};

export function getCommandName(cmd) {
  for (const dkey in commands) {
    if (commands[dkey] === cmd) {
      return `${dkey} - ${cmd} (0x${cmd.toString(16)})`;
    }
  }

  return `Unknown Command - ${cmd} (0x${cmd.toString(16)})`;
}

export default {
  getCommandName,
  commands,
};
